### ISSUE TITLE
请问 node-ffi 我写到主进程会报错 Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by webees** [starts2000/ElectronQQLogin#1]
我使用的是 electron-vue 脚手架
我在 src/main/index.js 中，也就是主进程中仅仅加了一句 

const ffi = require('ffi')

```
  Error: Could not locate the bindings file. Tried:
   → X:\git\electron_vue\build\binding.node
   → X:\git\electron_vue\build\Debug\binding.node
   → X:\git\electron_vue\build\Release\binding.node
   → X:\git\electron_vue\out\Debug\binding.node
   → X:\git\electron_vue\Debug\binding.node
   → X:\git\electron_vue\out\Release\binding.node
   → X:\git\electron_vue\Release\binding.node
   → X:\git\electron_vue\build\default\binding.node
   → X:\git\electron_vue\compiled\7.9.0\win32\ia32\binding.node
      at bindings (X:\git\electron_vue\dist\electron\main.js:5743:9)
      at Object.<anonymous> (X:\git\electron_vue\dist\electron\main.js:106:51)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
      at Object.<anonymous> (X:\git\electron_vue\dist\electron\main.js:7263:11)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
      at Object.module.exports.module.exports (X:\git\pubu.me\electron_vue\dist\electron\main.js:5399:11)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
      at Object.<anonymous> (X:\git\electron_vue\dist\electron\main.js:2956:70)
      at Object.module.exports.webpackEmptyContext.keys (X:\git\pubu.me\electron_vue\dist\electron\main.js:3081:30)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
```

我已经 rebuild 过了，如果加到渲染进程中就不会报错，发现你是直接加到主进程的，能告诉我怎么操作的吗？谢。

**Comment by webees** [comment]
一定要把ffi加到package.json的dependencies中！
