### ISSUE TITLE
ffi 始终运行失败

### ISSUE THREAD

**Issue by bacel12596** [starts2000/ElectronQQLogin#2]
请问安装ffi时有什么要注意的么 编译了很多次都成功，但是运行时就报错
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\ElectronQQLogin-master\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (E:\ElectronQQLogin-master\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (E:\ElectronQQLogin-master\node_modules\ref\lib\ref.js:5:47)

**Comment by starts2000** [comment]
参考：http://www.cnblogs.com/Starts_2000/p/electron-ffi.html
